### PR TITLE
Use .NET 4 for Windows natives (close #43)

### LINKED ISSUE #43: The 'find-window has stopped working' error appeared on any action in playground
Reproduced on Windows.
To reproduce run playground, open any browser and try to close or resize the opened browser.
TODO: check on the mac platform also

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by inikulin** [comment]
Seems like something wrong with npm and node 10 on Travis side once again. BTW can you update Travis configuration in context of this PR: just keep node 10 and node stable, e.g.: https://github.com/superroma/testcafe-hammerhead/blob/master/.travis.yml

**Comment by AndreyBelym** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
