### PR TITLE
Find-window MAC&WIN fixes

### PR DESCRIPTION
**Pull request by whitewolf2105**
Fixed find-window on Mac to test that window title contains pattern, not just equals to it
Fixed find-window on Win to avoid window title string allocation failure when marshalling it from win32api

\cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by whitewolf2105** [comment]
Spaces may be included in window name(title) and process name, so we're using newline as separator between window name and process name when returning them via stdout from our window finding module on MacOS.

**Comment by whitewolf2105** [comment]
FPR

**Comment by inikulin** [comment]
LGTM

**Comment by AlexanderMoskovkin** [comment]
LGTM

**Pull request merged**
