### PR TITLE
Open window implemented, playground and tests added (close #7, close #8)

### LINKED ISSUE #7: Implement browser open in natives
It should remove three args `path, cmd, pageUrl`

### LINKED ISSUE #8: Implement testing sandbox

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**
/cc @inikulin @whitewolf2105 
@VasilyStrelyaev please check test names it the test/tests/open-window-test.js file and the following strings:
"//NOTE: IE has two windows with the same title. We found actual window with the FindInIEWindow function"
"Take screenshot and save it to the default path or to the path: <input field>"

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
Tests failed. I'll fix it

**Comment by AlexanderMoskovkin** [comment]
FPR

**Comment by inikulin** [comment]
\r-

**Comment by inikulin** [comment]
BTW add node 10 and 12 to Travis testing targets.

**Comment by AlexanderMoskovkin** [comment]
FPR

**Comment by whitewolf2105** [comment]
LGTM

**Comment by inikulin** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
Test names OK
"take a screenshot and save it to the default path or the following one: "
what do you mean by saying "actual" about a window?

**Comment by inikulin** [comment]
https://github.com/AlexanderMoskovkin/testcafe-browser-natives/tree/open-window/src

I think we should rename binaries and source, it doesn't make sense to have `-window` suffix everythere: 
`close-window` -> `close`, `open-window` -> `open`, `find-window` is OK though.

And we still have things like `shotWindow` in https://github.com/AlexanderMoskovkin/testcafe-browser-natives/blob/open-window/src/natives.js 

\r-

**Comment by AlexanderMoskovkin** [comment]
@VasilyStrelyaev 
> what do you mean by saying "actual" about a window

it's the target window, the window that we should find.

**Comment by VasilyStrelyaev** [comment]
NOTE: IE has two windows with the same title. We've found the target window by using the FindInIEWindow function

/r-

**Comment by AlexanderMoskovkin** [comment]
>NOTE: IE has two windows with the same title. We've found the target window by using the FindInIEWindow function

Discussed with @VasilyStrelyaev and the final version is:
"//NOTE: IE has two windows with the same title. We are searching for the target window by using the FindInIEWindow function."

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by whitewolf2105** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
thanks

**Pull request merged**
