### PR TITLE
Add "main" field in package.json, npmignore things, rename test (fixes #18), bump version

### LINKED ISSUE #18: Rename test
`open-window-test.js` -> `open-test.js`

### PR DESCRIPTION
**Pull request by inikulin**
\cc @AlexanderMoskovkin @AndreyBelym

### CODE REVIEW

**Comment by AndreyBelym** [comment]
LGTM

**Comment by AndreyBelym** [comment]
Please, add ```.DS_Store``` to .npmignore.

**Comment by AndreyBelym** [comment]
Also there are small changes in two commits; maybe we can squash them.

**Comment by inikulin** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
LGTM

**Comment by AndreyBelym** [comment]
LGTM

**Pull request merged**
