### PR TITLE
Don't throw unableToFindBrowser (closes #50)

### LINKED ISSUE #50: We shouldn't throw error if we can't find browser file in `getBrowserInfo`
We shouldn't throw there for consistency - https://github.com/superroma/testcafe-browser-natives/blob/master/src/api/get-browser-info.js#L35

We should return null instead.

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm

**Comment by inikulin** [comment]
Can you publish v10.0.1 as well pls

**Comment by AlexanderMoskovkin** [comment]
Ok, we'll do it

**Pull request merged**
