### PR TITLE
Refactored build system

### PR DESCRIPTION
**Pull request by whitewolf2105**
/cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by inikulin** [comment]
\r-

**Comment by whitewolf2105** [comment]
FPR

**Comment by inikulin** [comment]
\r- due to comment above.

**Comment by whitewolf2105** [comment]
FPR

**Comment by whitewolf2105** [comment]
FPR

**Comment by inikulin** [comment]
\r- Can you squash after fixing once again? For commit just keep original message: 'Refactored build system'

**Comment by AlexanderMoskovkin** [comment]
LGTM

**Pull request merged**
